[tool.black]
line_length = 120
target_version = ["py39", "py310", "py311"]
skip_magic_trailing_comma = true

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 120
known_first_party = "userpass"
known_typing = "typing"
sections = ["FUTURE", "TYPING", "STDLIB", "FIRSTPARTY", "THIRDPARTY", "LOCALFOLDER"]